### PR TITLE
Add help file

### PR DESCRIPTION
**Pull request by tyru**
Hi.
How about adding help file?

And I have one question and one suggestion.

* What is this plugin's license? (for `License: ...` line)
* How about removing usage comment in plugin/oldfilesearch.vim ?

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Looks good, I will check the text sometime over the weekend.  The plugin license can be the same as for Vim itself.  I am OK with removing usage remarks from the script.  Thanks!

**Comment by tyru** [comment]
> I am OK with removing usage remarks from the script

This whole comment except "Date" seems to be moved to help file.
May I remove the whole comment?
https://github.com/pavoljuhas/oldfilesearch.vim/blob/e6b031212b66d8d925a2062791c905a1229af37f/plugin/oldfilesearch.vim#L1-L24

**Comment by pavoljuhas** [comment]
Hi Taru.  On a second thought, the help file seems to be an overkill.  It is basically the same text as in README and I'd prefer to maintain one file rather than two.  The plugin is also too simple to really need help.

I have updated the README text and added you as contributor within plugin notes.

**Comment by tyru** [comment]
okay.
so how about adding the license?

**Comment by pavoljuhas** [comment]
Yes, see 871b013734dd503f76d6af675b55161080563940.

**Comment by tyru** [comment]
Thanks!

**Pull request closed without merging**
